<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<LangVersion>Latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<!-- Debug is useless for a mod -->
		<DebugType>none</DebugType>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>

	<PropertyGroup>
		<TheLongDarkPath>D:\SteamLibrary\steamapps\common\TheLongDark</TheLongDarkPath>
	</PropertyGroup>

	<!-- List of used references -->
	<ItemGroup>
		<!-- This is the base reference. MUST EXIST -->
		<PackageReference Include="STBlade.Modding.TLD.CraftingRevisions" Version="2.2.3" />
		<PackageReference Include="STBlade.Modding.TLD.GearSpawner" Version="2.3.1" />
		<PackageReference Include="STBlade.Modding.TLD.Il2CppAssemblies.Windows" Version="2.51.0" />
		<PackageReference Include="STBlade.Modding.TLD.LocalizationUtilities" Version="2.0.0" />
		<PackageReference Include="STBlade.Modding.TLD.ModComponent" Version="6.2.3" />
		<!-- This is only if you use the ModSettings -->
		<PackageReference Include="STBlade.Modding.TLD.ModSettings" Version="1.9.0" />
		<!-- Only if you need ModData  -->
		<PackageReference Include="STBlade.Modding.TLD.ModData" Version="1.5.1" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	</ItemGroup>

	<!-- Most commonly used using's. Add to this so you dont need to define them in the cs files -->
	<ItemGroup>
		<Using Include="System.Reflection" />
		<Using Include="System.Diagnostics.CodeAnalysis" />
		<Using Include="Il2Cpp" />
		<Using Include="HarmonyLib" />
		<Using Include="MelonLoader" />
		<Using Include="UnityEngine" />
		<Using Include="ModSettings" />
		<Using Include="ModData" />
	</ItemGroup>

	<PropertyGroup>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<EnableDefaultCompileItems>false</EnableDefaultCompileItems>
	</PropertyGroup>

	<PropertyGroup>
		<AssemblyName>TheLongMood</AssemblyName>
		<RootNamespace>TheLongMood</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="Afflictions\Patches\AfflictionsEffects\Patches.cs" />
		<Compile Include="Afflictions\Boredom\Bored.cs" />
		<Compile Include="Afflictions\Boredom\Extremely Bored.cs" />
		<Compile Include="Afflictions\Boredom\Very Bored.cs" />
		<Compile Include="Afflictions\Depression\Hopeless.cs" />
		<Compile Include="Afflictions\Depression\Miserable.cs" />
		<Compile Include="Afflictions\Depression\Sad.cs" />
		<Compile Include="Afflictions\Depression\Weepy.cs" />
		<Compile Include="Afflictions\Patches\RepairOnCrashPatch.cs" />
		<Compile Include="Core.cs" />
		<Compile Include="ModSettings.cs" />
		<Compile Include="Afflictions\Patches\VisualPatch.cs" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="AfflictionComponent">
			<HintPath>$(TheLongDarkPath)\Mods\AfflictionComponent.dll</HintPath>
		</Reference>
	</ItemGroup>

	<!-- This is a build event. It will copy your dll to the currently defined TheLongDarkPath's Mods folder -->
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<!-- This copies the mods files to the games mod dir -->
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(TheLongDarkPath)/Mods" />
	</Target>
</Project>